package OOPSBannerApp;
/**
 * OOPSBannerApp UC2 - Banner Display Application
 * 
 * This class demonstrate the creation of a visual banner displaying the word "OOPS"
 * using ASCII art composed of asterisks (*) and spaces.The banner is printed to the 
 * console using individual print statements for each line ,creating a decorative 
 * text effect.
 * 
 * <p>The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to forming the letters o,o,p and s in a stylized format.
 * This extends a basic user story by adding visual presentation to a simple message output.
 * </p>
 * 
 * @author Developer
 * @version 2
 *
 */
//Extend the user Story 1 to display the message "OOPS" in a banner format
//using characters formed by spaces and asterisks (*) to create a visual
//effect for each letter in the message. Use print statements for each line
//instead of a loop.

public class oopsbannerappUC2 {
    //Main method to run the banner display
    //print each line of the OOPS banner to create the visual effect for the
    //message "OOPS". construct each line using string concatention.
    //Each line corresponds to a row in the banner for the letter o, o, p, s.
    //using individual print statements for each line.

    public static void main(String[] args) {
        System.out.println("   ***   " + " " + "     ***   " + " " + "   ****     "  + " " + "    ******    " );
        System.out.println(" **    ** " + " " + " **    ** " + " " + " **     **  "  + " " + " **         " );
        System.out.println("**      **" + " " + "**      **" + " " + "**       ** "  + " " + "**          " );
        System.out.println("**      **" + " " + "**      **" + " " + "**       ** "  + " " + "**          " );
        System.out.println("**      **" + " " + "**      **" + " " + "**      **  "  + " " + "   ****     " );
        System.out.println("**      **" + " " + "**      **" + " " + "** ****     "  + " " + "       **   " );
        System.out.println("**      **" + " " + "**      **" + " " + "**          "  + " " + "        **  " );
        System.out.println(" **    ** " + " " + " **    ** " + " " + "**          "  + " " + "        **  " );
        System.out.println("   ***   " + " " + "   ***   " + " " + " **           "  + " " + "  ******     " );
    }
    
}
